---
- name: Import AD users to OpenLdap
  hosts: ad-and-ldap
  gather_facts: false

  vars_files:
  - ./vault.yaml

  vars:
    ad_workdir: 'C:\Users\Administrator\Documents\'
    users_file: 'ad_users.ldif'
    ous_file: 'ad_ous.ldif'
    computers_file: 'ad_computers.ldif'
    script_file: "ldif-convert.js"


  tasks:
    # enter windows ad node and run ldifde command to output all AD OUs onto file.
    - name: Get AD Organizational Units
      ansible.windows.win_shell: 'ldifde -f {{ ad_workdir + ous_file }} -s douanes.lan -d "DC=douanes,DC=lan" -r "(objectClass=organizationalUnit)" -p subtree'
      when: inventory_hostname == "ad_server"
    
    # enter windows ad node and run ldifde command to output all AD users onto file.
    - name: Get AD users
      ansible.windows.win_shell: 'ldifde -f {{ ad_workdir + users_file }} -s douanes.sn -d "DC=douanes,DC=sn" -r "(objectClass=user)" -p subtree'
      when: inventory_hostname == "ad_server"

    # enter windows ad node and run ldifde command to output all AD computers onto file.
    - name: Get AD computers
      ansible.windows.win_shell: 'ldifde -f {{ ad_workdir + computers_file }} -s douanes.sn -d "DC=douanes,DC=sn" -r "(objectClass=computer)" -p subtree'
      when: inventory_hostname == "ad_server"


    # Copies the newly generated users file from AD to local machine
    - name: Save ad users to file
      fetch:
        src: "{{ item }}"
        dest: "./"
        flat: yes
      when: inventory_hostname == "ad_server"
      loop:
      - "{{ users_file }}"
      - "{{ ous_file }}"
      - "{{ computers_file }}"

      # Runs nodejs script to format generated OUs file into acceptable ldif file
    - name: Run nodejs script to format ad output to openldap ldif
      shell: AD_FILE="{{ playbook_dir + '/' + ad_ou_file }}" LDAP_FILE="{{ playbook_dir + '/' + ldap_ou_file }}" node {{ playbook_dir }}/ldif-convert.js
      when: inventory_hostname == "localhost"

      # Runs nodejs script to format generated users file into acceptable ldif file
    - name: Run nodejs script to format ad output to openldap ldif
      shell: AD_FILE="{{ playbook_dir + '/' + ad_users_file }}" LDAP_FILE="{{ playbook_dir + '/' + ldap_users_file }}" node {{ playbook_dir }}/ldif-convert.js
      when: inventory_hostname == "localhost"


     # Run ldapadd to add the OUs to ldap using the newly converted ldif file
    - name: Import newly created OUs ldif
      shell: ldapadd -x -f "{{ playbook_dir + '/' + ldap_ou_file }}" -D "cn=Admin,dc=douanes,dc=sn" -w {{ ldap_password }}
      when: inventory_hostname == "ldap_server"
     
      # Run ldapadd to add the users to ldap using the newly converted ldif file
     #- name: Import newly created ldif file
     # shell: ldapadd -x -f {{ ldap_users_file }} -D "cn=Admin,dc=douanes,dc=sn" -w {{ ldap_password }}
     #when: inventory_hostname == "ldap_server"
